[package]
name = "enarx-exploit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
nix = "0.24.1"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
bit_field = "0.10.1"
bytemuck = "1.9.1"